name: Deploy Lambda Function

on:
  push:
    branches:
      - main
    paths:
      - "apps/lambda/**"
      - ".github/workflows/deploy.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.15.6"

      - name: Install Turbo and Run Prune
        run: |
          pnpm add -g turbo
          turbo prune lambda
          cd out

      - name: Run Install and Build
        run: |
          pnpm install
          pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build --build-arg LAMBDA_DIR=firstLambda -t my-lambda-one .
          docker build --build-arg LAMBDA_DIR=secondLambda -t my-lambda-two .

      - name: Tag Docker Image
        run: |
          docker tag my-lambda-one:latest ${{ steps.login-ecr.outputs.registry }}/my-lambda-one:latest
          docker tag my-lambda-two:latest ${{ steps.login-ecr.outputs.registry }}/my-lambda-two:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/my-lambda-one:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/my-lambda-two:latest

      - name: Update Lambda Functions
        run: |
          aws lambda update-function-code \
            --function-name firstLambda \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/my-lambda-one:latest
          aws lambda update-function-code \
            --function-name secondLambda \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/my-lambda-two:latest
