name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.15.6"

      - name: Install Turbo and Run Prune
        run: |
          pnpm add -g turbo
          turbo prune lambda

      - name: Run Install and Build
        run: |
          cd out
          pnpm install
          pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker container
        uses: docker/build-push-action@v6
        with:
          context: ./out
          file: ../Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/my-lambda-one:latest
          secrets: |
            "TEST_ENV=${{ secrets.TEST_ENV }}"

      - name: Update Lambda Functions
        run: |
          aws lambda update-function-code \
            --function-name firstLambda \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/my-lambda-one:latest
